print("Hello from Jenkins automation!")
print("changes Made")
print("Test1")
print("Test2")
print("Test 3")
print("Test 4")
print("Test5")
print("Test6")
print("Test7")
print("added a jekins user")
print("Some changed made in jenkins")
print("new mail added to jenkins")

